import json
import os
import re

GENERATED_MARKER = "# Generated by Git Gallery Runner"
COMPOSE_FILE = "docker-compose.yml"


def _read_json(path):
    if not os.path.exists(path):
        return None
    with open(path, "r", encoding="utf-8") as handle:
        return json.load(handle)


def _write_text(path, content):
    os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
    with open(path, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(content)


def has_compose(path):
    return any(
        os.path.exists(os.path.join(path, name))
        for name in ("docker-compose.yml", "docker-compose.yaml", "compose.yml", "compose.yaml")
    )


def _has_package(path, subdir="."):
    return os.path.exists(os.path.join(path, subdir, "package.json"))


def _find_dir(path, names):
    for name in names:
        if _has_package(path, name) or os.path.exists(os.path.join(path, name)):
            return name
    return None


def _package_uses(pkg, package_name):
    if not pkg:
        return False
    for section in ("dependencies", "devDependencies"):
        if package_name in pkg.get(section, {}):
            return True
    return False


def _npm_script(pkg, names, default):
    scripts = (pkg or {}).get("scripts", {})
    for name in names:
        if name in scripts:
            return scripts[name]
    return default


def _detect_container_port(pkg, fallback=3000):
    scripts = (pkg or {}).get("scripts", {})
    start = scripts.get("start", "") + " " + scripts.get("dev", "")
    if "-p 3000" in start or "--port 3000" in start or "PORT=3000" in start:
        return 3000
    if "-p 4000" in start or "--port 4000" in start:
        return 4000
    if _package_uses(pkg, "next"):
        return 3000
    return fallback


def _has_prisma(path, subdir="."):
    return os.path.exists(os.path.join(path, subdir, "prisma", "schema.prisma"))


def _has_python_app(path):
    return any(
        os.path.exists(os.path.join(path, name))
        for name in ("requirements.txt", "pyproject.toml", "Pipfile")
    )


def _has_laravel(path):
    return (
        os.path.exists(os.path.join(path, "artisan"))
        and os.path.exists(os.path.join(path, "composer.json"))
    )


def _python_entrypoint(path):
    for module in ("app", "main", "wsgi"):
        if os.path.exists(os.path.join(path, f"{module}.py")):
            if module == "wsgi":
                return 'CMD ["gunicorn", "wsgi:app", "-b", "0.0.0.0:8000"]'
            return f'CMD ["uvicorn", "{module}:app", "--host", "0.0.0.0", "--port", "8000"]'
    if os.path.exists(os.path.join(path, "manage.py")):
        return 'CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]'
    return 'CMD ["python", "main.py"]'


def _node_dockerfile(workdir_name, pkg, port):
    build_step = ""
    scripts = (pkg or {}).get("scripts", {})
    if "build" in scripts:
        build_step = "RUN npm run build\n"
    start_cmd = _npm_script(pkg, ("start", "dev"), "npm start")
    if start_cmd.startswith("npm "):
        cmd = start_cmd.replace("npm ", "").split()
        command = 'CMD ["npm", "' + '", "'.join(cmd) + '"]'
    else:
        command = f'CMD ["sh", "-c", "{start_cmd}"]'
    return f"""{GENERATED_MARKER}
FROM node:20-alpine
WORKDIR /app
COPY package.json package-lock.json* ./
RUN npm install
COPY . .
{build_step}EXPOSE {port}
{command}
"""


def _laravel_dockerfile():
    return f"""{GENERATED_MARKER} (Laravel)
FROM php:8.3-apache

RUN apt-get update && apt-get install -y \\
    git curl unzip libpng-dev libjpeg62-turbo-dev libfreetype6-dev \\
    libzip-dev libonig-dev libxml2-dev libicu-dev \\
    && docker-php-ext-configure gd --with-freetype --with-jpeg \\
    && docker-php-ext-install -j$(nproc) pdo_mysql mbstring exif pcntl bcmath gd zip intl opcache calendar \\
    && a2enmod rewrite \\
    && rm -rf /var/lib/apt/lists/*

COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

RUN curl -fsSL https://deb.nodesource.com/setup_20.x | bash - \\
    && apt-get install -y nodejs \\
    && rm -rf /var/lib/apt/lists/*

ENV APACHE_DOCUMENT_ROOT=/var/www/html/public
RUN sed -ri -e 's!/var/www/html!${{APACHE_DOCUMENT_ROOT}}!g' /etc/apache2/sites-available/*.conf \\
    && sed -ri -e 's!/var/www/!${{APACHE_DOCUMENT_ROOT}}!g' /etc/apache2/conf-available/*.conf

WORKDIR /var/www/html
COPY . .
RUN git config --global --add safe.directory /var/www/html \\
    && composer install --no-interaction --prefer-dist --optimize-autoloader \\
    && npm install \\
    && npm run build \\
    && chown -R www-data:www-data storage bootstrap/cache

COPY docker/entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
EXPOSE 80
ENTRYPOINT ["/entrypoint.sh"]
CMD ["apache2-foreground"]
"""


def _laravel_compose(port=80):
    return f"""{GENERATED_MARKER} (Laravel)
services:
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: laravel-crm
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', '127.0.0.1', '-uroot', '-psecret']
      interval: 5s
      timeout: 5s
      retries: 15

  app:
    build: .
    ports:
      - '{port}:{port}'
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      APP_URL: http://localhost:{port}
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: laravel-crm
      DB_USERNAME: root
      DB_PASSWORD: secret
    volumes:
      - app_storage:/var/www/html/storage

volumes:
  mysql_data:
  app_storage:
"""


def _laravel_entrypoint():
    return """#!/bin/sh
set -e

cd /var/www/html

echo "Waiting for MySQL at ${DB_HOST}..."
until php -r "
try {
    new PDO(
        'mysql:host=${DB_HOST};port=${DB_PORT:-3306}',
        '${DB_USERNAME}',
        '${DB_PASSWORD}'
    );
    exit(0);
} catch (Throwable \\$e) {
    exit(1);
}
" 2>/dev/null; do
    sleep 2
done

if [ ! -f .env ]; then
    cp .env.example .env
fi

set_env() {
    key="$1"
    val="$2"
    if grep -q "^${key}=" .env; then
        sed -i "s|^${key}=.*|${key}=${val}|" .env
    else
        printf '%s=%s\\n' "$key" "$val" >> .env
    fi
}

set_env APP_URL "${APP_URL:-http://localhost}"
set_env DB_CONNECTION "${DB_CONNECTION:-mysql}"
set_env DB_HOST "${DB_HOST:-mysql}"
set_env DB_PORT "${DB_PORT:-3306}"
set_env DB_DATABASE "${DB_DATABASE:-laravel-crm}"
set_env DB_USERNAME "${DB_USERNAME:-root}"
set_env DB_PASSWORD "${DB_PASSWORD:-secret}"

if [ ! -f storage/installed ]; then
    echo "Running Laravel installer..."
    php artisan krayin-crm:install --skip-env-check --skip-admin-creation --no-interaction \\
        || php artisan migrate --force
    echo "Application installed" > storage/installed
fi

exec "$@"
"""


def _python_dockerfile(path):
    req = "requirements.txt" if os.path.exists(os.path.join(path, "requirements.txt")) else "pyproject.toml"
    install = (
        "RUN pip install --no-cache-dir -r requirements.txt"
        if req == "requirements.txt"
        else "RUN pip install --no-cache-dir ."
    )
    return f"""{GENERATED_MARKER}
FROM python:3.11-slim
WORKDIR /app
COPY {req} ./
{install}
COPY . .
EXPOSE 8000
{_python_entrypoint(path)}
"""


def _static_dockerfile():
    return f"""{GENERATED_MARKER}
FROM nginx:alpine
COPY . /usr/share/nginx/html
EXPOSE 80
"""


def detect_layout(path):
    if has_compose(path):
        return {"kind": "existing"}

    frontend = _find_dir(path, ("frontend", "client", "web"))
    backend = _find_dir(path, ("backend", "server", "api"))

    if frontend and backend and (_has_package(path, frontend) or _has_package(path, backend)):
        return {"kind": "multi", "frontend": frontend, "backend": backend}

    if _has_laravel(path):
        return {"kind": "laravel", "port": 80}

    if _has_package(path):
        pkg = _read_json(os.path.join(path, "package.json"))
        if _package_uses(pkg, "next"):
            return {"kind": "nextjs", "port": _detect_container_port(pkg, 3000)}
        return {"kind": "node", "port": _detect_container_port(pkg, 3000)}

    if _has_python_app(path):
        return {"kind": "python", "port": 8000}

    if os.path.exists(os.path.join(path, "index.html")):
        return {"kind": "static", "port": 80}

    return {"kind": "unknown"}


def _compose_with_postgres(services_body):
    return f"""{GENERATED_MARKER}
services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5

{services_body}
volumes:
  pgdata:
  app_storage:
"""


def generate_stack(path, repo):
    layout = detect_layout(path)
    logs = []

    if layout["kind"] == "existing":
        stack = infer_stack_from_compose(path)
        return True, stack, "docker-compose already exists.\n"

    if layout["kind"] == "unknown":
        return False, None, "Could not detect project type for auto-dockerize.\n"

    frontend_port, backend_port = int(repo.get("port") or 3000), int(repo.get("backend_port") or 4000)

    if layout["kind"] == "multi":
        frontend = layout["frontend"]
        backend = layout["backend"]
        frontend_pkg = _read_json(os.path.join(path, frontend, "package.json"))
        backend_pkg = _read_json(os.path.join(path, backend, "package.json"))
        fe_port = _detect_container_port(frontend_pkg, 3000)
        be_port = _detect_container_port(backend_pkg, 4000)

        _write_text(
            os.path.join(path, frontend, "Dockerfile"),
            _node_dockerfile(frontend, frontend_pkg, fe_port),
        )
        logs.append(f"created {frontend}/Dockerfile")

        if _has_python_app(os.path.join(path, backend)):
            _write_text(os.path.join(path, backend, "Dockerfile"), _python_dockerfile(os.path.join(path, backend)))
        else:
            _write_text(
                os.path.join(path, backend, "Dockerfile"),
                _node_dockerfile(backend, backend_pkg, be_port),
            )
        logs.append(f"created {backend}/Dockerfile")

        use_postgres = _has_prisma(path, backend) or _has_prisma(path, frontend)
        backend_env = f"""      PORT: {be_port}
      FRONTEND_URL: http://localhost:{frontend_port}"""
        if use_postgres:
            backend_env = f"""      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/app
{backend_env}"""

        backend_depends_block = ""
        if use_postgres:
            backend_depends_block = """    depends_on:
      postgres:
        condition: service_healthy
"""

        backend_block = f"""  backend:
    build:
      context: ./{backend}
      dockerfile: Dockerfile
    ports:
      - '{be_port}:{be_port}'
    environment:
{backend_env}
{backend_depends_block}    volumes:
      - app_storage:/app/storage

  frontend:
    build:
      context: ./{frontend}
      dockerfile: Dockerfile
    ports:
      - '{fe_port}:{fe_port}'
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:{backend_port}/api
    depends_on:
      - backend
"""
        if use_postgres:
            compose = _compose_with_postgres(backend_block)
        else:
            compose = f"""{GENERATED_MARKER}
services:
{backend_block}
volumes:
  app_storage:
"""

        _write_text(os.path.join(path, COMPOSE_FILE), compose)
        logs.append(f"created {COMPOSE_FILE}")
        stack = {
            "kind": "multi",
            "frontend_service": "frontend",
            "backend_service": "backend",
            "frontend_container_port": fe_port,
            "backend_container_port": be_port,
        }
        return True, stack, "\n".join(logs) + "\n"

    if layout["kind"] in {"nextjs", "node"}:
        pkg = _read_json(os.path.join(path, "package.json"))
        port = layout["port"]
        _write_text(os.path.join(path, "Dockerfile"), _node_dockerfile(".", pkg, port))
        compose = f"""{GENERATED_MARKER}
services:
  app:
    build: .
    ports:
      - '{port}:{port}'
    environment:
      PORT: {port}
"""
        _write_text(os.path.join(path, COMPOSE_FILE), compose)
        logs.extend(["created Dockerfile", f"created {COMPOSE_FILE}"])
        return True, {"kind": "single", "service": "app", "container_port": port}, "\n".join(logs) + "\n"

    if layout["kind"] == "laravel":
        port = layout["port"]
        _write_text(os.path.join(path, "docker", "entrypoint.sh"), _laravel_entrypoint())
        _write_text(os.path.join(path, "Dockerfile"), _laravel_dockerfile())
        _write_text(os.path.join(path, COMPOSE_FILE), _laravel_compose(port))
        logs.extend(["created docker/entrypoint.sh", "created Dockerfile", f"created {COMPOSE_FILE}"])
        return True, {"kind": "single", "service": "app", "container_port": port}, "\n".join(logs) + "\n"

    if layout["kind"] == "python":
        _write_text(os.path.join(path, "Dockerfile"), _python_dockerfile(path))
        port = layout["port"]
        compose = f"""{GENERATED_MARKER}
services:
  app:
    build: .
    ports:
      - '{port}:{port}'
"""
        _write_text(os.path.join(path, COMPOSE_FILE), compose)
        logs.extend(["created Dockerfile", f"created {COMPOSE_FILE}"])
        return True, {"kind": "single", "service": "app", "container_port": port}, "\n".join(logs) + "\n"

    if layout["kind"] == "static":
        _write_text(os.path.join(path, "Dockerfile"), _static_dockerfile())
        compose = f"""{GENERATED_MARKER}
services:
  app:
    build: .
    ports:
      - '8080:80'
"""
        _write_text(os.path.join(path, COMPOSE_FILE), compose)
        logs.extend(["created Dockerfile", f"created {COMPOSE_FILE}"])
        return True, {"kind": "single", "service": "app", "container_port": 80, "host_port": 8080}, "\n".join(logs) + "\n"

    return False, None, "Unsupported project layout.\n"


def _compose_path(path):
    for name in ("docker-compose.yml", "docker-compose.yaml", "compose.yml", "compose.yaml"):
        candidate = os.path.join(path, name)
        if os.path.exists(candidate):
            return candidate
    return None


def parse_compose_services(path):
    compose_path = _compose_path(path)
    if not compose_path:
        return []

    services = []
    in_services = False
    with open(compose_path, "r", encoding="utf-8") as handle:
        for line in handle:
            if re.match(r"^services:\s*$", line):
                in_services = True
                continue
            if not in_services:
                continue
            match = re.match(r"^  ([a-zA-Z0-9_-]+):\s*$", line)
            if match:
                services.append(match.group(1))
            elif line.strip() and re.match(r"^[a-zA-Z]", line):
                break
    return services


def service_container_port(path, service_name):
    compose_path = _compose_path(path)
    if not compose_path:
        return None

    in_service = False
    in_ports = False
    with open(compose_path, "r", encoding="utf-8") as handle:
        for line in handle:
            if re.match(rf"^  {re.escape(service_name)}:\s*$", line):
                in_service = True
                in_ports = False
                continue
            if in_service and re.match(r"^  [a-zA-Z0-9_-]+:\s*$", line):
                break
            if in_service and re.match(r"^    ports:\s*$", line):
                in_ports = True
                continue
            if in_service and in_ports:
                explicit = re.search(r"['\"]?(\d+):(\d+)['\"]?", line)
                if explicit:
                    return int(explicit.group(2))
                env_style = re.search(r":(\d+)\s*['\"]?\s*$", line.strip())
                if env_style:
                    return int(env_style.group(1))
                if line.strip() and not line.startswith("      "):
                    in_ports = False
    return None


def infer_stack_from_compose(path):
    services = parse_compose_services(path)
    if not services:
        return {"kind": "unknown"}

    service_set = set(services)
    pairs = [
        ("frontend", "backend", 3000, 4000, True),
        ("admin", "api", 3000, 4000, False),
        ("web", "api", 3000, 4000, False),
        ("client", "server", 3000, 4000, False),
    ]
    for fe, be, fe_default, be_default, use_next_env in pairs:
        if fe in service_set and be in service_set:
            return {
                "kind": "multi",
                "frontend_service": fe,
                "backend_service": be,
                "frontend_container_port": service_container_port(path, fe) or fe_default,
                "backend_container_port": service_container_port(path, be) or be_default,
                "use_next_env": use_next_env,
            }

    for name in ("app", "web", "frontend", "admin", "runtime"):
        if name in service_set:
            return {
                "kind": "single",
                "service": name,
                "container_port": service_container_port(path, name) or 3000,
            }

    return {"kind": "none"}


def ensure_docker_stack(path, repo):
    if has_compose(path):
        stack = repo.get("docker_stack") or infer_stack_from_compose(path)
        return True, stack, "Using existing docker-compose.\n"

    ok, stack, log = generate_stack(path, repo)
    return ok, stack, log
